#spring:
#  data:
#    mongodb:
#      uri: mongodb+srv://admin:root@stockmanagementsystemda.x4gsheb.mongodb.net/?retryWrites=true&w=majority&appName=stockManagementSystemData
#      database: userData